// Code generated by entc, DO NOT EDIT.

package transaction

import (
	"github.com/confus1on/mbeledos/ent/schema"
)

const (
	// Label holds the string label denoting the transaction type in the database.
	Label = "transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderphone holds the string denoting the orderphone vertex property in the database.
	FieldOrderphone = "orderphone"
	// FieldNamabengkel holds the string denoting the namabengkel vertex property in the database.
	FieldNamabengkel = "namabengkel"

	// Table holds the table name of the transaction in the database.
	Table = "transactions"
)

// Columns holds all SQL columns are transaction fields.
var Columns = []string{
	FieldID,
	FieldOrderphone,
	FieldNamabengkel,
}

var (
	fields = schema.Transaction{}.Fields()

	// descOrderphone is the schema descriptor for orderphone field.
	descOrderphone = fields[0].Descriptor()
	// OrderphoneValidator is a validator for the "orderphone" field. It is called by the builders before save.
	OrderphoneValidator = descOrderphone.Validators[0].(func(string) error)

	// descNamabengkel is the schema descriptor for namabengkel field.
	descNamabengkel = fields[1].Descriptor()
	// NamabengkelValidator is a validator for the "namabengkel" field. It is called by the builders before save.
	NamabengkelValidator = descNamabengkel.Validators[0].(func(string) error)
)
