// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/confus1on/mbeledos/ent/user"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nohp", Type: field.TypeString, Default: user.DefaultNohp},
		{Name: "nama", Type: field.TypeString, Default: user.DefaultNama},
		{Name: "tgl_lahir", Type: field.TypeString, Default: user.DefaultTglLahir},
		{Name: "alamat", Type: field.TypeString, Default: user.DefaultAlamat},
		{Name: "level", Type: field.TypeInt},
		{Name: "image", Type: field.TypeString, Default: user.DefaultImage},
		{Name: "kategori_level", Type: field.TypeString, Default: user.DefaultKategoriLevel},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
