// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"log"

	"github.com/facebookincubator/ent/dialect/sql"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 ENT_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExampleBengkel() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the bengkel's edges.

	// create bengkel vertex with its edges.
	b := client.Bengkel.
		Create().
		SetKodeBengkel("string").
		SetNamaBengkel("string").
		SetAlamatBengkel("string").
		SetLatitude(1).
		SetLongitude(1).
		SaveX(ctx)
	log.Println("bengkel created:", b)

	// query edges.

	// Output:
}
func ExampleUser() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the user's edges.

	// create user vertex with its edges.
	u := client.User.
		Create().
		SetNohp("string").
		SetNama("string").
		SetTglLahir("string").
		SetAlamat("string").
		SetLevel(1).
		SetImage("string").
		SetKategoriLevel("string").
		SaveX(ctx)
	log.Println("user created:", u)

	// query edges.

	// Output:
}
