// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/confus1on/mbeledos/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	nohp           *string
	nama           *string
	tgl_lahir      *string
	alamat         *string
	level          *int
	image          *string
	kategori_level *string
}

// SetNohp sets the nohp field.
func (uc *UserCreate) SetNohp(s string) *UserCreate {
	uc.nohp = &s
	return uc
}

// SetNillableNohp sets the nohp field if the given value is not nil.
func (uc *UserCreate) SetNillableNohp(s *string) *UserCreate {
	if s != nil {
		uc.SetNohp(*s)
	}
	return uc
}

// SetNama sets the nama field.
func (uc *UserCreate) SetNama(s string) *UserCreate {
	uc.nama = &s
	return uc
}

// SetNillableNama sets the nama field if the given value is not nil.
func (uc *UserCreate) SetNillableNama(s *string) *UserCreate {
	if s != nil {
		uc.SetNama(*s)
	}
	return uc
}

// SetTglLahir sets the tgl_lahir field.
func (uc *UserCreate) SetTglLahir(s string) *UserCreate {
	uc.tgl_lahir = &s
	return uc
}

// SetNillableTglLahir sets the tgl_lahir field if the given value is not nil.
func (uc *UserCreate) SetNillableTglLahir(s *string) *UserCreate {
	if s != nil {
		uc.SetTglLahir(*s)
	}
	return uc
}

// SetAlamat sets the alamat field.
func (uc *UserCreate) SetAlamat(s string) *UserCreate {
	uc.alamat = &s
	return uc
}

// SetNillableAlamat sets the alamat field if the given value is not nil.
func (uc *UserCreate) SetNillableAlamat(s *string) *UserCreate {
	if s != nil {
		uc.SetAlamat(*s)
	}
	return uc
}

// SetLevel sets the level field.
func (uc *UserCreate) SetLevel(i int) *UserCreate {
	uc.level = &i
	return uc
}

// SetImage sets the image field.
func (uc *UserCreate) SetImage(s string) *UserCreate {
	uc.image = &s
	return uc
}

// SetNillableImage sets the image field if the given value is not nil.
func (uc *UserCreate) SetNillableImage(s *string) *UserCreate {
	if s != nil {
		uc.SetImage(*s)
	}
	return uc
}

// SetKategoriLevel sets the kategori_level field.
func (uc *UserCreate) SetKategoriLevel(s string) *UserCreate {
	uc.kategori_level = &s
	return uc
}

// SetNillableKategoriLevel sets the kategori_level field if the given value is not nil.
func (uc *UserCreate) SetNillableKategoriLevel(s *string) *UserCreate {
	if s != nil {
		uc.SetKategoriLevel(*s)
	}
	return uc
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if uc.nohp == nil {
		v := user.DefaultNohp
		uc.nohp = &v
	}
	if uc.nama == nil {
		v := user.DefaultNama
		uc.nama = &v
	}
	if uc.tgl_lahir == nil {
		v := user.DefaultTglLahir
		uc.tgl_lahir = &v
	}
	if uc.alamat == nil {
		v := user.DefaultAlamat
		uc.alamat = &v
	}
	if uc.level == nil {
		return nil, errors.New("ent: missing required field \"level\"")
	}
	if err := user.LevelValidator(*uc.level); err != nil {
		return nil, fmt.Errorf("ent: validator failed for field \"level\": %v", err)
	}
	if uc.image == nil {
		v := user.DefaultImage
		uc.image = &v
	}
	if uc.kategori_level == nil {
		v := user.DefaultKategoriLevel
		uc.kategori_level = &v
	}
	return uc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	var (
		builder = sql.Dialect(uc.driver.Dialect())
		u       = &User{config: uc.config}
	)
	tx, err := uc.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	insert := builder.Insert(user.Table).Default()
	if value := uc.nohp; value != nil {
		insert.Set(user.FieldNohp, *value)
		u.Nohp = *value
	}
	if value := uc.nama; value != nil {
		insert.Set(user.FieldNama, *value)
		u.Nama = *value
	}
	if value := uc.tgl_lahir; value != nil {
		insert.Set(user.FieldTglLahir, *value)
		u.TglLahir = *value
	}
	if value := uc.alamat; value != nil {
		insert.Set(user.FieldAlamat, *value)
		u.Alamat = *value
	}
	if value := uc.level; value != nil {
		insert.Set(user.FieldLevel, *value)
		u.Level = *value
	}
	if value := uc.image; value != nil {
		insert.Set(user.FieldImage, *value)
		u.Image = *value
	}
	if value := uc.kategori_level; value != nil {
		insert.Set(user.FieldKategoriLevel, *value)
		u.KategoriLevel = *value
	}

	id, err := insertLastID(ctx, tx, insert.Returning(user.FieldID))
	if err != nil {
		return nil, rollback(tx, err)
	}
	u.ID = int(id)
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return u, nil
}
