// Code generated by entc, DO NOT EDIT.

package user

import (
	"github.com/confus1on/mbeledos/ent/schema"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNohp holds the string denoting the nohp vertex property in the database.
	FieldNohp = "nohp"
	// FieldNama holds the string denoting the nama vertex property in the database.
	FieldNama = "nama"
	// FieldTglLahir holds the string denoting the tgl_lahir vertex property in the database.
	FieldTglLahir = "tgl_lahir"
	// FieldAlamat holds the string denoting the alamat vertex property in the database.
	FieldAlamat = "alamat"
	// FieldLevel holds the string denoting the level vertex property in the database.
	FieldLevel = "level"
	// FieldImage holds the string denoting the image vertex property in the database.
	FieldImage = "image"
	// FieldKategoriLevel holds the string denoting the kategori_level vertex property in the database.
	FieldKategoriLevel = "kategori_level"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns are user fields.
var Columns = []string{
	FieldID,
	FieldNohp,
	FieldNama,
	FieldTglLahir,
	FieldAlamat,
	FieldLevel,
	FieldImage,
	FieldKategoriLevel,
}

var (
	fields = schema.User{}.Fields()

	// descNohp is the schema descriptor for nohp field.
	descNohp = fields[0].Descriptor()
	// DefaultNohp holds the default value on creation for the nohp field.
	DefaultNohp = descNohp.Default.(string)

	// descNama is the schema descriptor for nama field.
	descNama = fields[1].Descriptor()
	// DefaultNama holds the default value on creation for the nama field.
	DefaultNama = descNama.Default.(string)

	// descTglLahir is the schema descriptor for tgl_lahir field.
	descTglLahir = fields[2].Descriptor()
	// DefaultTglLahir holds the default value on creation for the tgl_lahir field.
	DefaultTglLahir = descTglLahir.Default.(string)

	// descAlamat is the schema descriptor for alamat field.
	descAlamat = fields[3].Descriptor()
	// DefaultAlamat holds the default value on creation for the alamat field.
	DefaultAlamat = descAlamat.Default.(string)

	// descLevel is the schema descriptor for level field.
	descLevel = fields[4].Descriptor()
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator = descLevel.Validators[0].(func(int) error)

	// descImage is the schema descriptor for image field.
	descImage = fields[5].Descriptor()
	// DefaultImage holds the default value on creation for the image field.
	DefaultImage = descImage.Default.(string)

	// descKategoriLevel is the schema descriptor for kategori_level field.
	descKategoriLevel = fields[6].Descriptor()
	// DefaultKategoriLevel holds the default value on creation for the kategori_level field.
	DefaultKategoriLevel = descKategoriLevel.Default.(string)
)
